analisis/urls.py
from django.conf.urls import url

from . import views

app_name = 'analisis'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'resultados/$', views.resultados, name='resultados'),
]

mapas/urls.py
from django.conf.urls import url

from . import views

app_name = 'mapas'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^mapas/', include('mapas.urls')),
    url(r'^analisis/', include('analisis.urls')),
    url(r'^acerca/', include('acerca.urls')),
    url(r'^admin/', admin.site.urls),
]

mapas/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render

import pandas as pd
import numpy as np
import json
import simplejson

def volcar(archivo, delimitador):
    datos = pd.read_csv(archivo,delimiter=delimitador,decimal=".",index_col=0)
    return datos

class ComplexEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, complex):             return [obj.real, obj.imag]
        # Let the base class default method raise the TypeError
        return json.JSONEncoder.default(self, obj)

# Create your views here.
def index(request):

    # MacOS
    # ruta = "/Users/jgarcia/diplomado/analisis/static/analisis/"
    # Windows
    ruta = "C:/Users/jgr70/Documents/diplomado/analisis/static/analisis/"

    area_selvatica = volcar(ruta + 'files/area_selvatica.csv', ',')
    poblacion_urbana = volcar(ruta + 'files/poblacion_urbana.csv', ',')
    gases_efecto_invernadero = volcar(ruta + 'files/gases_efecto_invernadero.csv', ',')

    list_idx_selvatica = area_selvatica.index.tolist()
    list_idx_poblacion = poblacion_urbana.index.tolist()
    list_idx_gases = gases_efecto_invernadero.index.tolist()

    json_paises_area_selvatica = json.dumps(list_idx_selvatica,
        separators=(',',':')
    )

    json_poblacion_urbana = simplejson.dumps(list_idx_poblacion,
        default=lambda a: "[%s,%s]" % (str(type(a)), a.pk)
    )

    json_gases_efecto_invernadero = simplejson.dumps(list_idx_gases,
        default=lambda a: "[%s,%s]" % (str(type(a)), a.pk)
    )

    return render(request, 'mapas/index.html', {
        'titulo': 'Dashboard - Selección de país',
        'json_paises_area_selvatica': json_paises_area_selvatica,
        'json_poblacion_urbana': json_poblacion_urbana,
        'json_gases_efecto_invernadero': json_gases_efecto_invernadero
    })

mapas/templates/mapas/index.html
{% extends 'analisis/layout.html' %}

{% load static %}

{% block csspage %}
<link rel="stylesheet" href="{% static 'mapas/jqvmap/jqvmap.css' %}" />
{% endblock %}

{% block content %}
<div class="row">

  <div class="col-xs-12 col-md-6">
    <section class="panel">
			<header class="panel-heading">
				<h2 class="panel-title">Sudamerica</h2>
			</header>
			<div class="panel-body">
				<div id="south-america" style="width: 100%; height: 400px;"></div>
			</div>
		</section>
  </div>

</div>

<form action="{% url 'analisis:index' %}" name="frmAnalizar" id="frmAnalizar" method="post">
    {% csrf_token %}
    <input type="hidden" name="Pais" id="Pais">
</form>

{% endblock %}

{% block jspage %}

    <script src="{% static 'mapas/js/jquery.blockUI.js' %}"></script>
    <script src="{% static 'mapas/jqvmap/jquery.vmap.js' %}"></script>
    <script src="{% static 'mapas/jqvmap/data/jquery.vmap.sampledata.js' %}"></script>
    <script src="{% static 'mapas/jqvmap/maps/continents/jquery.vmap.south-america.js' %}"></script>

    <script type="text/javascript">

    json_paises_area_selvatica = '{{json_paises_area_selvatica}}';
    json_paises_area_selvatica = JSON.parse(json_paises_area_selvatica.replace(/&quot;/g,'"'));

    json_poblacion_urbana = '{{json_poblacion_urbana}}';
    json_poblacion_urbana = JSON.parse(json_poblacion_urbana.replace(/&quot;/g,'"'));

    json_gases_efecto_invernadero = '{{json_gases_efecto_invernadero}}';
    json_gases_efecto_invernadero = JSON.parse(json_gases_efecto_invernadero.replace(/&quot;/g,'"'));

    jQuery(document).ready(function() {

        jQuery('#south-america').vectorMap({
            map: 'south-america_en',
            backgroundColor: '#ffffff',
            color: '#ffffff',
            hoverOpacity: 0.7,
            selectedColor: '#666666',
            enableZoom: true,
            showTooltip: true,
            values: sample_data,
            scaleColors: ['#C8EEFF', '#006491'],
            normalizeFunction: 'polynomial',
            onRegionClick: function(element, code, region)
            {
                if(jQuery.inArray(region,json_paises_area_selvatica) != -1 && jQuery.inArray(region,json_poblacion_urbana) && jQuery.inArray(region,json_gases_efecto_invernadero)){

                    $.blockUI({ message: '<h1>Por favor espere...</h1>' });
                    jQuery('#Pais').val(region);
                    jQuery('#frmAnalizar').submit();
                }
                else{
                    alert("El pais seleccionado no cuenta con la información suficiente para ser visualizado.");
                }

            },
        });
    });
    </script>

{% endblock %}